// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// lm_fit
Eigen::VectorXd lm_fit(Eigen::VectorXd y, Eigen::MatrixXd X, Eigen::VectorXd weights);
RcppExport SEXP _hlm_lm_fit(SEXP ySEXP, SEXP XSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(lm_fit(y, X, weights));
    return rcpp_result_gen;
END_RCPP
}
// lvlm_fit
Eigen::VectorXd lvlm_fit(Eigen::VectorXd y2, Eigen::MatrixXd Z, Eigen::VectorXd gamma0);
RcppExport SEXP _hlm_lvlm_fit(SEXP y2SEXP, SEXP ZSEXP, SEXP gamma0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y2(y2SEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type gamma0(gamma0SEXP);
    rcpp_result_gen = Rcpp::wrap(lvlm_fit(y2, Z, gamma0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hlm_lm_fit", (DL_FUNC) &_hlm_lm_fit, 3},
    {"_hlm_lvlm_fit", (DL_FUNC) &_hlm_lvlm_fit, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_hlm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
