# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lm_fit <- function(y, X, weights) {
    .Call(`_hlm_lm_fit`, y, X, weights)
}

lvlm_fit <- function(y2, Z, gamma0) {
    .Call(`_hlm_lvlm_fit`, y2, Z, gamma0)
}

